name: BackendTest

on:
  workflow_dispatch:
    
permissions:
  contents: read
  
  
jobs:
  test:
    runs-on: ubuntu-latest #24.04-arm
    env:
       CONFIG : ${{ vars.CONFIG }}
       
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Setup Tesseract
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr

    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh   

        
    - name: Run Test
      run : |
        ${{ secrets.TEST_CMD }}
        
 
